all: software-install-good-practices.pdf


software-install-good-practices.pdf: software-install-good-practices.tex
	pdflatex software-install-good-practices.tex
	pdflatex software-install-good-practices.tex
